CREATE TABLE IF NOT EXISTS playlists (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS songs (
    id               INT GENERATED BY DEFAULT AS IDENTITY,
    title            VARCHAR(200) NOT NULL,
    artist           VARCHAR(150) NOT NULL,
    album            VARCHAR(150),
    genre            VARCHAR(80),
    duration_seconds INT          NOT NULL,
    playlist_code    VARCHAR(50),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_songs_playlist FOREIGN KEY (playlist_code) REFERENCES playlists (code) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS users (
    id            INT GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(64)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username)
);

-- Auto-update trigger
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_playlists_updated_at ON playlists;
CREATE TRIGGER trg_playlists_updated_at
BEFORE UPDATE ON playlists FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_songs_updated_at ON songs;
CREATE TRIGGER trg_songs_updated_at
BEFORE UPDATE ON songs FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── Seed data ─────────────────────────────────────────────────

INSERT INTO playlists (code, name) VALUES
('CHILL', 'Chill Vibes'),
('HYPE', 'Hype / Workout'),
('LOFI', 'Lo-Fi Study'),
('POP', 'Pop Hits'),
('ROCK', 'Rock Classics'),
('RNB', 'R&B Soul'),
('JAZZ', 'Jazz & Blues')
ON CONFLICT DO NOTHING;

INSERT INTO songs (title, artist, album, genre, duration_seconds, playlist_code) VALUES
('Blinding Lights',    'The Weeknd',  'After Hours',           'Pop',  200, 'POP'),
('Shape of You',       'Ed Sheeran',  'Divide',                'Pop',  234, 'POP'),
('Levitating',         'Dua Lipa',    'Future Nostalgia',      'Pop',  203, 'POP'),
('Bohemian Rhapsody',  'Queen',       'A Night at the Opera',  'Rock', 354, 'ROCK'),
('Hotel California',   'Eagles',      'Hotel California',      'Rock', 391, 'ROCK'),
('Back In Black',      'AC/DC',       'Back In Black',         'Rock', 255, 'ROCK'),
('Stay With Me',       'Sam Smith',   'In the Lonely Hour',    'R&B',  172, 'RNB'),
('Redbone',            'Childish Gambino', 'Awaken, My Love!', 'R&B',  325, 'RNB'),
('Drivers License',    'Olivia Rodrigo', 'SOUR',               'Pop',  242, 'CHILL'),
('Good Days',          'SZA',         'Good Days',             'R&B',  274, 'CHILL'),
('Lofi Hip Hop Study', 'ChilledCow',  'Study Beats Vol 1',     'Lo-Fi',180, 'LOFI'),
('Coffee Shop Vibes',  'Study Beats', 'Relaxing Study Music',  'Lo-Fi',210, 'LOFI'),
('Stronger',           'Kanye West',  'Graduation',            'Hip-Hop',312,'HYPE'),
('Lose Yourself',      'Eminem',      '8 Mile Soundtrack',     'Hip-Hop',326,'HYPE'),
('All That Jazz',      'Chicago Cast','Chicago Soundtrack',    'Jazz', 188, 'JAZZ')
ON CONFLICT DO NOTHING;

INSERT INTO users (username, password_hash) VALUES
('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9'),
('user',  '9b8769a4a742959a2d0298c36fb70623f2a2d0d78301f98e487dad71f98f6ad4')
ON CONFLICT DO NOTHING;
